#!/usr/bin/env node
/**
 * Regenerates `src/data/codex.js` from the upstream awesome-lidar list.
 *
 *   node tools/build_codex.mjs [path-or-url]
 *
 * With no argument it fetches the canonical README from GitHub. Every top-level
 * bullet in the list becomes one codex entry; sub-bullets (YouTube / ROS driver
 * / paper links) are intentionally dropped -- the in-game codex links straight
 * to the primary resource and defers the rest to the upstream list.
 */
import { writeFile, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const SRC = process.argv[2] ||
  'https://raw.githubusercontent.com/szenergy/awesome-lidar/master/README.md';

const SECTION_KIND = {
  'Manufacturers': 'manufacturer',
  'Datasets': 'dataset',
  'Libraries': 'library',
  'Frameworks': 'framework',
  'Algorithms': 'algorithm',
  'Simulators': 'simulator',
  'Related awesome': 'related',
  'Others': 'tool',
};

const stripMarkdown = (s) => s
  .replace(/\[([^\]]*)\]\([^)]*\)/g, '$1')   // inline links -> label
  .replace(/!\[[^\]]*\]/g, '')               // badge images
  .replace(/\s+/g, ' ')
  .replace(/^[-–—\s]+/, '')
  .trim();

const truncate = (s, n = 190) => {
  s = stripMarkdown(s);
  return s.length > n ? `${s.slice(0, n - 3).replace(/[,;.\s]+\S*$/, '')}…` : s;
};

async function load(src) {
  if (/^https?:/.test(src)) {
    const res = await fetch(src);
    if (!res.ok) throw new Error(`fetch ${src} -> ${res.status}`);
    return res.text();
  }
  return readFile(src, 'utf8');
}

function parse(markdown) {
  const items = [];
  let section = '';
  let subsection = '';
  for (const line of markdown.split('\n')) {
    let m;
    if ((m = line.match(/^##\s+(.*)$/))) { section = m[1].trim(); subsection = ''; continue; }
    if ((m = line.match(/^###\s+(.*)$/))) { subsection = m[1].trim(); continue; }
    if (section === 'Contents' || !line.startsWith('- [')) continue;
    m = line.match(/^- \[([^\]]+)\]\(([^)]+)\)\s*-?\s*(.*)$/);
    if (!m) continue;
    items.push({
      k: SECTION_KIND[section] ?? 'other',
      g: subsection || section,
      n: stripMarkdown(m[1]),
      u: m[2],
      d: truncate(m[3]),
    });
  }
  return items;
}

const here = dirname(fileURLToPath(import.meta.url));
const items = parse(await load(SRC));
if (items.length < 50) throw new Error(`only parsed ${items.length} entries -- upstream format changed?`);

const groups = [...new Set(items.map((i) => i.g))];
const out = `// AUTO-GENERATED by tools/build_codex.mjs from https://github.com/szenergy/awesome-lidar
// Do not edit by hand -- re-run \`npm run codex\` to refresh.
export const CODEX = ${JSON.stringify(items, null, 1)};

export const CODEX_GROUPS = ${JSON.stringify(groups, null, 1)};
`;
await writeFile(resolve(here, '../viewer/src/data/codex.js'), out);
console.log(`codex: ${items.length} entries across ${groups.length} groups`);
